name: deck-compress-web-app
services:
- name: web
  source_dir: /web_app
  github:
    repo: your-username/deck-compress
    branch: main
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: PORT
    value: "8080"
  - key: PYTHONPATH
    value: "/workspace/src"
